
version: '3.8'

volumes:
  postgres:
    driver: local

services:
  api:
    container_name: api
    restart: always
    build:
      context: ./
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./src:/usr/src/app/src
    environment:
       - PORT=3000
       - DATABASE_URL=postgres://test_user:secret@postgres:5432/update_balance_db
    ports:
      - 3000:3000
  
  postgres:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=test_user
      - POSTGRES_DB=update_balance_db
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "update_balance_db", "-U", "test_user"]
      interval: 5s
      timeout: 5s
      retries: 5